image: Visual Studio 2017

install:
  - set QTDIR=C:\Qt\5.5\mingw492_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
  - git submodule update --init --recursive

before_build:
    - cmake -G "Visual Studio 15 2017 Win64" .

build_script:
  - cd TGTs
  - qmake TGTs.pro
  - mingw32-make
