sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt55[QTPACKAGE]
  - sudo apt-get install libsfml-dev
  - sudo apt-get install libgtest-dev
  - sudo apt-get install cmake
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd -	

script:
  - source /opt/qt55/bin/qt55-env.sh
  - ls
  - sudo mkdir release && cd release
  - /opt/qt55/bin/qmake ../TGTs/TGTs.pro -o Makefile
  - make
